/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface GenomicCard {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface GenomicCardAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'GenomicCard': Components.GenomicCard;
  }

  interface StencilIntrinsicElements {
    'genomic-card': Components.GenomicCardAttributes;
  }


  interface HTMLGenomicCardElement extends Components.GenomicCard, HTMLStencilElement {}
  var HTMLGenomicCardElement: {
    prototype: HTMLGenomicCardElement;
    new (): HTMLGenomicCardElement;
  };

  interface HTMLElementTagNameMap {
    'genomic-card': HTMLGenomicCardElement
  }

  interface ElementTagNameMap {
    'genomic-card': HTMLGenomicCardElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
